name: Pull-request to main

on:
  pull_request:
    branches: ["main"]

jobs:
  run-e2e-tests:
    steps:
      - name: Trigger workflow dispatch
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -d '{"ref": "${{ github.ref }}"}' \
            https://api.github.com/repos/Harbour-Enterprises/superdoc-tests/actions/workflows/173620104/dispatches 